FROM ubuntu:14.04
# 12.04
MAINTAINER Olof Hagsand <olof@hagsand.se>
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
    curl
COPY libcligen.so.@CLIGEN_VERSION@ /usr/lib/
COPY libclixon.so.@CLIXON_VERSION@ /usr/lib/
RUN ldconfig
COPY ./grideye_agent /usr/local/bin/
CMD ["grideye_agent", "-R", "IOREADFILE", "-c", "1M", "-u", "http://grideye.nordu.net", "-I", "ba43a60e-eeb2-48f8-803d-5a3477feb3b0", "-N", "docker-grideye", "-p", "udp", ":7878"]
EXPOSE 7878 7878/udp






